# Generated by Django 4.2.4 on 2023-08-22 06:49

import django.core.validators
from django.db import migrations, models
import test_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_employee_cv_alter_employee_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.FileField(upload_to=test_app.models.employee_picture_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=test_app.models.employee_picture_path),
        ),
    ]
